### ISSUE TITLE
Merge repository

### ISSUE THREAD

**Issue by StefansArya** [MirazMac/YouScrape#2]
Hi,
I just found that you want to make a similar repository like [LittleYoutube](https://github.com/StefansArya/LittleYoutube-PHP).
Would you like to help me rather than build another one by yourself? :smile:

**Comment by MirazMac** [comment]
Well thanks. Nice code you have there. But **YouScrape** isn't actually the same as yours. It intends to bypass the free API rate limit of YouTube Data API v3. I'll continue with this I think :)

**Comment by StefansArya** [comment]
I see, good luck with your code XD
