### ISSUE TITLE
Fetch all / latest Community Tab Post

### ISSUE THREAD

**Issue by Kenuux** [MirazMac/YouScrape#3]
Hello, 

Could you maybe implement a feature to fetch all or the latest community tab post? ( for example: https://www.youtube.com/channel/UC5DHDP4t6M53jN9Gv8QZq4A/community )

Thanks

**Comment by MirazMac** [comment]
That's a nice feature idea, I'll see what I can do about it.
Thanks

**Comment by MirazMac** [comment]
Sorry, I've tried my best but at the moment the YouTube mobile version doesn't have any endpoints for the community tab. In fact it doesn't even have the community tab on the mobile site. However, I tried scraping via the desktop ajax endpoint but unlike the mobile endpoints those are protected by various tokens and checksum based verification, which will take way too long to bypass and would break the base of this library. However, I'll look into the endpoints of the YouTube android app and see if I can do anything. Till then, this issue will remain closed.
Thanks

**Comment by Kenuux** [comment]
Okay, thanks! - Does maybe this link help you out? https://www.youtube.com/channel/UC5DHDP4t6M53jN9Gv8QZq4A/community?disable_polymer=1&dp_lcl=1 - I'm not really an expert in this section, but it seems not protected.

**Comment by MirazMac** [comment]
Well, I'm not talking about the page itself. I'm talking about the XHR endpoints. Scrapping by the html tags isn't a good choice or approach as they tend to change often and are DOM/Regex heavy and I'm not willing to do that for this library.
